import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export interface PrintableItinerary {
  title?: string;
  summary?: string;
  notes?: Array<{ label?: string; value?: unknown }>;
}

function safeFileName(value: string) {
  const cleaned = value
    .trim()
    .replace(/[^a-z0-9]+/gi, "-")
    .replace(/^-+|-+$/g, "");
  return `${cleaned || "itinerary"}.pdf`;
}

export function exportItineraryPdf(itinerary: PrintableItinerary) {
  const title = String(itinerary.title || "My itinerary").trim();
  const summary = String(itinerary.summary || "").trim();
  const notes = Array.isArray(itinerary.notes) ? itinerary.notes : [];
  const document = new jsPDF({
    unit: "mm",
    format: "a4",
    orientation: "portrait",
  });
  const pageWidth = document.internal.pageSize.getWidth();
  const pageHeight = document.internal.pageSize.getHeight();
  const margin = 16;

  document.setFillColor(15, 74, 145);
  document.rect(0, 0, pageWidth, 34, "F");
  document.setTextColor(255, 255, 255);
  document.setFont("helvetica", "bold");
  document.setFontSize(17);
  document.setFontSize(11);
  document.text("SOUSA MURRAY PLANEIA", margin, 14);
  document.setFont("helvetica", "normal");
  document.setFontSize(9);
  document.text("Personalised itinerary", margin, 21);

  document.setTextColor(17, 24, 39);
  document.setFont("helvetica", "bold");
  document.setFontSize(20);
  const titleLines = document.splitTextToSize(title, pageWidth - margin * 2);
  document.text(titleLines, margin, 48);
  let cursor = 48 + titleLines.length * 8;

  if (summary) {
    document.setFont("helvetica", "normal");
    document.setFontSize(10.5);
    document.setTextColor(71, 85, 105);
    const summaryLines = document.splitTextToSize(
      summary,
      pageWidth - margin * 2,
    );
    document.text(summaryLines, margin, cursor);
    cursor += summaryLines.length * 5 + 7;
  }

  autoTable(document, {
    startY: cursor,
    margin: { left: margin, right: margin, bottom: 18 },
    head: [["Itinerary detail", "Information"]],
    body: notes.length
      ? notes.map((note) => [
          String(note.label || "Detail"),
          String(note.value ?? ""),
        ])
      : [["Plan details", "No additional itinerary details were supplied."]],
    theme: "grid",
    styles: {
      font: "helvetica",
      fontSize: 9.5,
      cellPadding: 4,
      overflow: "linebreak",
      valign: "top",
    },
    headStyles: { fillColor: [15, 74, 145], textColor: 255, fontStyle: "bold" },
    columnStyles: {
      0: { cellWidth: 52, fontStyle: "bold", textColor: [30, 64, 175] },
    },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    didDrawPage: ({ pageNumber }) => {
      document.setDrawColor(226, 232, 240);
      document.line(
        margin,
        pageHeight - 13,
        pageWidth - margin,
        pageHeight - 13,
      );
      document.setFont("helvetica", "normal");
      document.setFontSize(8);
      document.setTextColor(100, 116, 139);
      document.text(
        "Generated by Sousa Murray Planeia · Please confirm live prices, times and availability.",
        margin,
        pageHeight - 8,
      );
      document.text(`Page ${pageNumber}`, pageWidth - margin, pageHeight - 8, {
        align: "right",
      });
    },
  });

  document.save(safeFileName(title));
}
